export const CREATE_TRIP_AND_DAYS = "CREATE_TRIP_AND_DAYS"
export const RETRIEVE_TRIPS = "RETRIEVE_TRIPS"
export const UPDATE_TRIP = "UPDATE_TRIP"
export const DELETE_TRIP = "DELETE_TRIP"
export const DELETE_ALL_TRIPS = "DELETE_ALL_TRIPS"

export const CREATE_SLOT = "CREATE_SLOT"
export const UPDATE_SLOT = "UPDATE_SLOT"
export const DELETE_SLOT = "DELETE_SLOT"

export const CREATE_CARER = "CREATE_CARER"
export const RETRIEVE_CARERS = "RETRIEVE_CARERS"